### <font color="brown">NumPy - Continued</font>

In [1]:
import numpy as np

---

**The max function is not a ufunc (universal function - the second parameter is a scalar that refers to the "axis"**

In [ ]:
arr3 = [3,5,1,15,7]
print(arr3)

In [ ]:
np.max(arr3,0)  # max is not binary unfunc, second arg for max is "axis"

**The binary ufunc name (maximum) is different from unary ufunc name (max) because the 2nd argument has a different meaning from one to the other**

In [ ]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

In [ ]:
print(np.max(arr2d, 1))  # maximums for each of the rows (across columns), dimension argument is 1

In [ ]:
print(np.max(arr2d, 0))  # maximums for each of the columns (down rows), dimension argument is 0

In [ ]:
arr = np.array([1,2,np.nan,4,5])
arr

**fmax is a universal function (ufunc) that works like maximum, difference is it ignores NaN**

In [ ]:
print(arr3)
print(arr)

In [ ]:
np.maximum(arr3,arr)

In [ ]:
np.fmax(arr3,arr)   

**greater ufunc**

In [ ]:
arr1 = [1,2,3,4]
arr2 = [2,1,2,3]
np.greater(arr1,arr2)  

---

#### <font color="brown">Using NumPy random module</font>

**randint function**

In [2]:
np.random.randint(-50,0)  
# single random integer between -50 (inclusive) and 0 (exclusive)

-6

In [3]:
# same as basic Python random.randint except in basic Python random.randint, 2nd arg is inclusive
import random
random.randint(-50,0)

-10

In [4]:
np.random.randint(1,100,5)  
# 5 random integers between 1 (inclusive) and 100 (exclusive)

array([24, 70, 43, 61, 18])

In [5]:
np.random.randint(1,100,(2,3))  
# fill (2,3) array with random integers in range 1..99

array([[ 7, 71, 40],
       [63, 84, 22]])

**random function**

In [6]:
np.random.random(5)  # 5 random reals 0 (inclusive) thru 1 (exclusive)

array([0.23338149, 0.82839698, 0.4912235 , 0.11543156, 0.04646357])

In [7]:
# basic Python version returns a single random number in the range [0,1)
random.random()

0.152495565713196

In [8]:
np.random.random((3,2)) * 5

array([[2.89285307, 2.11486753],
       [3.18175775, 2.04704658],
       [3.46042536, 3.04009457]])

**choice function**

In [9]:
nlst = [1,5,3,2,19,12,22,18,75,2,-10,0,15]
np.random.choice(nlst,3)  # 3 random selections from nlst

array([19,  2,  1])

In [10]:
# Python random.choice gives a single item
random.choice(nlst)  

5

In [11]:
np.random.choice(nlst,8)  

array([ 2,  0,  3, 19,  2,  2, 75, 75])

In [12]:
np.random.choice(nlst,size=8,replace=False)   # no duplicates

array([  0,  75,  22,   2,   1, -10,   2,  18])

**shuffle function**

In [13]:
arrs = np.arange(1,10)
arrs

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.random.shuffle(arrs)
arrs

array([7, 8, 2, 3, 5, 4, 1, 9, 6])

**<font color="red">Note: shuffle changes the original array</font>**

In [15]:
arrs2d = np.random.randint(1,50,(3,4))
arrs2d

array([[37, 29,  5,  4],
       [17,  6, 47, 44],
       [30, 34,  5, 17]])

In [16]:
np.random.shuffle(arrs2d)  # only shuffles rows 
arrs2d

array([[37, 29,  5,  4],
       [30, 34,  5, 17],
       [17,  6, 47, 44]])

**<font color="red">shuffle only shuffles the rows (in general, only shuffles 1st axis of a multidimensional array)</font>**

In [17]:
arr3d = np.arange(18).reshape(3,3,2)
print(arr3d)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]


In [18]:
np.random.shuffle(arr3d)
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

**permutation function**

In [19]:
arrp = np.arange(1,10)
np.random.permutation(arrp)

array([4, 6, 1, 8, 5, 7, 9, 3, 2])

In [20]:
arrp

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**<font color="red">Note that permutation does NOT change the original array</font>**

In [21]:
arrp2d = np.random.randint(1,50,(5,3))
arrp2d

array([[ 1, 36, 10],
       [26, 16, 32],
       [28, 38, 22],
       [42, 40, 12],
       [26, 27, 31]])

In [22]:
np.random.permutation(arrp2d)  # only permutes rows

array([[ 1, 36, 10],
       [26, 27, 31],
       [26, 16, 32],
       [42, 40, 12],
       [28, 38, 22]])

**<font color="red">Like shuffle, permutation only permutes the rows (in general, only permutes 1st axis of a multidimensional array)</font>**

In [23]:
arrp2d  # original not changed

array([[ 1, 36, 10],
       [26, 16, 32],
       [28, 38, 22],
       [42, 40, 12],
       [26, 27, 31]])

---

#### <font color="brown">NumPy math and stats functions ("reductions")</font>
**functions min, max, mean, sum, std, cumsum**

In [24]:
arrx = np.random.randint(1,20,5)
print(arrx)
print(arrx.max())  
print(arrx.min())
print(arrx.mean())
print(arrx.sum())
print(arrx.std())
print(arrx.cumsum())

[15 13 16  6 17]
17
6
13.4
67
3.9293765408777004
[15 28 44 50 67]


In [25]:
# Alternatively, can use same-named np functions instead of ndarray methods
print(arrx)
print(np.max(arrx))  
print(np.min(arrx))
print(np.mean(arrx))
print(np.sum(arrx))
print(np.std(arrx))
print(np.cumsum(arrx))

[15 13 16  6 17]
17
6
13.4
67
3.9293765408777004
[15 28 44 50 67]


**functions argmax, argmin**

In [26]:
narr = np.array([3,1,-10,5,2,0,-10])
narr

array([  3,   1, -10,   5,   2,   0, -10])

In [27]:
# index of minimum value
print(narr.argmin())  # ndarray method
print(np.argmin(narr))  # np function

2
2


**<font color="red">Using axis for reductions on rows only or columns only</font>**

In [28]:
arr2d = np.arange(1,10).reshape(3,3)[[1,0,2]][:,[1,2,0]]
arr2d

array([[5, 6, 4],
       [2, 3, 1],
       [8, 9, 7]])

In [29]:
# ndarray method versions
print('max in each column: ',end='')
print(arr2d.max(axis=0))
print('row index of max in each column: ',end='')
print(arr2d.argmax(axis=0))
print('max in each row: ',end='')
print(arr2d.max(axis=1))
print('column index of max in each row: ',end='')
print(arr2d.argmax(axis=1))
print()
print('min in each column: ',end='')
print(arr2d.min(axis=0))
print('row index of min in each column: ',end='')
print(arr2d.argmin(axis=0))
print('min in each row: ',end='')
print(arr2d.min(axis=1))
print('column index of min in each row: ',end='')
print(arr2d.argmin(axis=1))

max in each column: [8 9 7]
row index of max in each column: [2 2 2]
max in each row: [6 3 9]
column index of max in each row: [1 1 1]

min in each column: [2 3 1]
row index of min in each column: [1 1 1]
min in each row: [4 1 7]
column index of min in each row: [2 2 2]


In [30]:
# np function versions
print('max in each column: ',end='')
print(np.max(arr2d,axis=0))
print('row index of max in each column: ',end='')
print(np.argmax(arr2d,axis=0))
print('max in each row: ',end='')
print(np.max(arr2d,axis=1))
print('column index of max in each row: ',end='')
print(np.argmax(arr2d,axis=1))

max in each column: [8 9 7]
row index of max in each column: [2 2 2]
max in each row: [6 3 9]
column index of max in each row: [1 1 1]


**<font color="red">Without axis argument, functions apply to entire 2d array<font>**

In [31]:
arr2d

array([[5, 6, 4],
       [2, 3, 1],
       [8, 9, 7]])

In [32]:
arr2d.mean()

5.0

In [33]:
arr2d.mean(axis=1)  # mean of column values for each row

array([5., 2., 8.])

In [34]:
arr2d.mean(axis=0)  # mean of row values for each column

array([5., 6., 4.])

In [35]:
arr2d.cumsum(axis=0)  # cumulative sum for each column

array([[ 5,  6,  4],
       [ 7,  9,  5],
       [15, 18, 12]])

---

#### <font color="brown">Unique</font>

In [36]:
scores = np.array([10,9,9,8,2,3,2,7,5,8])
np.unique(scores)   

array([ 2,  3,  5,  7,  8,  9, 10])

**Gives <font color="red">sorted</font> list of unique values**

In [37]:
arr = [[ 3,  3,  9],
       [10, 12,  1],
       [ 9,  8,  4],
       [ 2,  3, 12]]

In [38]:
np.unique(arr)

array([ 1,  2,  3,  4,  8,  9, 10, 12])

---

#### <font color="brown">Sorting</font>

In [39]:
a = np.array([3,-1,2,5,15,22,-10,85])
print(a)

[  3  -1   2   5  15  22 -10  85]


**np sort function**

In [40]:
np.sort(a)

array([-10,  -1,   2,   3,   5,  15,  22,  85])

In [41]:
print(a) 

[  3  -1   2   5  15  22 -10  85]


**<font color="red">Note that sort function does not change the original array</font>**

**ndarray sort method**

In [43]:
a.sort()  
print(a)

[-10  -1   2   3   5  15  22  85]


**<font color="red">Note that ndarray sort method changes the original array</font>**

In [44]:
a = np.array([3,-1,2,5,15,22,-10,85])
print(a)

[  3  -1   2   5  15  22 -10  85]


**np argsort function**

In [45]:
# positions of sorted values
sort_ix = np.argsort(a)
print(np.sort(a))
print(sort_ix)

[-10  -1   2   3   5  15  22  85]
[6 1 2 0 3 4 5 7]


**ndarray argsort method**

In [48]:
print(a.argsort())

[6 1 2 0 3 4 5 7]


**sort on 2D array**

In [49]:
a = [3,-1,2,5,15,22,-10,85]
b = [9,2,15,10,1,3,-2,5]
c = np.array([a,b])
print(c)

[[  3  -1   2   5  15  22 -10  85]
 [  9   2  15  10   1   3  -2   5]]


In [50]:
np.sort(c)

array([[-10,  -1,   2,   3,   5,  15,  22,  85],
       [ -2,   1,   2,   3,   5,   9,  10,  15]])

**<font color="red">Note that each row is individually sorted</font>**

In [51]:
np.argsort(c)  

array([[6, 1, 2, 0, 3, 4, 5, 7],
       [6, 4, 1, 5, 7, 0, 3, 2]])

In [52]:
np.argsort(c)[:,-3:]  # positions of max 3 values in each row

array([[4, 5, 7],
       [0, 3, 2]])

In [53]:
arr = np.random.randint(1,13,(4,3))
print(arr)

[[ 6  2  7]
 [ 2  6 10]
 [ 5  4  5]
 [ 2 11  6]]


In [54]:
np.sort(arr,axis=0)   # sort along columns

array([[ 2,  2,  5],
       [ 2,  4,  6],
       [ 5,  6,  7],
       [ 6, 11, 10]])

In [55]:
np.argsort(arr,axis=0)

array([[1, 0, 2],
       [3, 2, 3],
       [2, 1, 0],
       [0, 3, 1]])

In [56]:
np.sort(arr,axis=1)  # sort each row

array([[ 2,  6,  7],
       [ 2,  6, 10],
       [ 4,  5,  5],
       [ 2,  6, 11]])

In [57]:
np.sort(arr)  # axis=1 is default

array([[ 2,  6,  7],
       [ 2,  6, 10],
       [ 4,  5,  5],
       [ 2,  6, 11]])

---

#### <font color="brown">where function</font>

In [59]:
xlst = [1,2,3,4,5]
ylst = [6,7,8,9,10]
condlst = [True, False, True, True, False]

In [60]:
# want value from xarr if cond is True, otherwise value from yarr
res = [x if c else y
           for x,y,c in zip(xlst, ylst, condlst)]
res

[1, 7, 3, 4, 10]

**Using where function to conditionally manipulate items of array**

In [61]:
# above list comprehension is equivalent to this
np.where(condlst, xlst, ylst)

array([ 1,  7,  3,  4, 10])

**Either or both of 2nd and 3rd arguments to np.where can be scalars**

In [62]:
arr = np.random.randint(-5,5,(4,4))
print(arr,'\n')

# replace all negative values with -1 and other values with 1
arrx = np.where(arr < 0, -1, 1)
print(arrx)

[[ 3  1  0  1]
 [ 2  1  2  1]
 [ 0  0 -5 -5]
 [ 2 -3  4  3]] 

[[ 1  1  1  1]
 [ 1  1  1  1]
 [ 1  1 -1 -1]
 [ 1 -1  1  1]]


In [63]:
# replace only negative values with -1
arrx = np.where(arr < 0, -1, arr)
print(arrx)

[[ 3  1  0  1]
 [ 2  1  2  1]
 [ 0  0 -1 -1]
 [ 2 -1  4  3]]


---

#### <font color="brown">Boolean arrays</font>
**Boolean values are coerced to 1 (True) and 0 (False)**

##### Exercise: Find number of positive values in an array

In [64]:
arr = np.array([1,-5,2,3,-4,6])
arr > 0

array([ True, False,  True,  True, False,  True])

In [65]:
(arr > 0).sum()    # number of True values 

4

In [66]:
print((arr > 0).any())
print((arr > 0).all())

True
False


---

#### <font color="brown">Linear Algebra</font>

In [67]:
narr = np.arange(0,32).reshape(4,8)
narr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

**Matrix Transpose**

In [71]:
narr.T  # transpose, rows become columns and vice versa

array([[ 0,  8, 16, 24],
       [ 1,  9, 17, 25],
       [ 2, 10, 18, 26],
       [ 3, 11, 19, 27],
       [ 4, 12, 20, 28],
       [ 5, 13, 21, 29],
       [ 6, 14, 22, 30],
       [ 7, 15, 23, 31]])

In [73]:
# alternatively
narr.transpose()

array([[ 0,  8, 16, 24],
       [ 1,  9, 17, 25],
       [ 2, 10, 18, 26],
       [ 3, 11, 19, 27],
       [ 4, 12, 20, 28],
       [ 5, 13, 21, 29],
       [ 6, 14, 22, 30],
       [ 7, 15, 23, 31]])

In [74]:
narr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

**<font color="red">Note that transpose does not change the original array</font>**

**np function version**

In [75]:
np.transpose(narr)

array([[ 0,  8, 16, 24],
       [ 1,  9, 17, 25],
       [ 2, 10, 18, 26],
       [ 3, 11, 19, 27],
       [ 4, 12, 20, 28],
       [ 5, 13, 21, 29],
       [ 6, 14, 22, 30],
       [ 7, 15, 23, 31]])

In [76]:
narr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

**Matrix Multiplication**

In [77]:
mat1 = np.arange(1,7).reshape(2,3)
mat1

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
mat2 = np.arange(1,7).reshape(3,2)
mat2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [79]:
np.dot(mat1,mat2)  # matrix multiply mat1 with mat2

array([[22, 28],
       [49, 64]])

In [80]:
mat2, mat1

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [81]:
np.dot(mat2,mat1)  # matrix multiply mat2 with mat1

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [82]:
mat3 = np.array([-1,1,3,2,2,4]).reshape(2,3)
mat3

array([[-1,  1,  3],
       [ 2,  2,  4]])

In [83]:
mat1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [86]:
np.dot(mat1.T,mat3)  # transpose mat1, then matrix multiply with mat3

array([[ 7,  9, 19],
       [ 8, 12, 26],
       [ 9, 15, 33]])

In [87]:
np.dot(np.array([1,2,3]), np.array([1,2,3]))  # dot product of two vectors

14